### ISSUE TITLE
Gh-pages

### ISSUE THREAD

**Issue by ViniFreiri** [franciane-lark/Siteada#1]
Olá, td bem? Venho aqui te recomendar a criar um branch chamado "gh-pages", depois de criado, o próprio GitHub hospeda teus sites no domínio .io e assim todos que acessam o seu perfil podem ver seus sites no ar.

**Comment by franciane-lark** [comment]
Olá, obrigada pela dica. Estou fazendo uns testes aqui.

**Comment by ViniFreiri** [comment]
Fico grato em ajudar meus colegas devs
